### ISSUE TITLE
this commit leak aws creds

### ISSUE THREAD

**Issue by abuvanth** [Vipisanan/SpringBootS3bucketAWS#1]
https://github.com/Vipisanan/SpringBootS3bucketAWS/commit/43ca99c50fca729309de91514e944b9e67eb5f89

**Comment by Vipisanan** [comment]
If i delete the bucket. Is it ok?

**Comment by abuvanth** [comment]
rotate aws key

**Comment by tutorgeeks** [comment]
Good work !!! @abuvanth

**Comment by Vipisanan** [comment]
@abuvanth ### 

> how do you find it?

**Comment by tutorgeeks** [comment]
@Vipisanan : I hope you've rotated the AWS credentials.
Just a suggestion: While deleting the sensitive credentials don't use commit message like "**remove access and secret key**", it will help the attacker to search easily.
